name: Unzip File

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip the uploaded .zip file
        run: |
          unzip -o SC web.zip -d hasil-unzip

      - name: Commit & Push hasil unzip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hasil-unzip
          git commit -m "Unzipped folderku.zip automatically"
          git push
